---
header:
  - license:
      spdx-id: Apache-2.0
      copyright-owner: eni-controller
      pattern: |
        Copyright|Apache-2.0
      content: |
        Copyright 2022 Authors of eni-controller
        SPDX-License-Identifier: Apache-2.0
    paths:
      - '**/*.go'
      - '**/*.sh'
    paths-ignore:
      - 'vendor'
    comment: on-failure
  - license:
      content: |
        Copyright 2023 The Eni-controller Authors
        SPDX-License-Identifier: Apache-2.0
    paths:
      - '**/*.go'
      - '**/*.sh'
    paths-ignore:
      - 'vendor'
    comment: on-failure
