apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.controller.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      {{- include "enipam.Controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if or .Values.controller.podAnnotations .Values.global.commonAnnotations }}
      annotations:
        {{- if .Values.global.commonAnnotations }}
        {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if .Values.controller.podAnnotations }}
        {{- include "tplvalues.render" ( dict "value" .Values.controller.podAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
        {{- end }}
      labels:
        {{- include "enipam.Controller.selectorLabels" . | nindent 8 }}
        {{- if .Values.global.commonLabels }}
        {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if .Values.controller.podLabels }}
        {{- include "tplvalues.render" ( dict "value" .Values.controller.podLabels "context" $ ) | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.controller.image.imagePullSecrets }}
      imagePullSecrets:
      {{- with .Values.controller.image.imagePullSecrets }}
      {{- toYaml . | trim | nindent 6 }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ .Values.controller.name | trunc 63 | trimSuffix "-" }}
      priorityClassName: {{ default "system-node-critical" .Values.controller.priorityClassName }}
      {{- if .Values.controller.hostnetwork }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- else }}
      hostNetwork: false
      dnsPolicy: ClusterFirst
      {{- end }}
      restartPolicy: Always
      {{- with .Values.controller.tolerations }}
      tolerations:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.controller.affinity }}
      affinity:
      {{- include "tplvalues.render" (dict "value" .Values.controller.affinity "context" $) | nindent 6 }}
      {{- else }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    {{- include "enipam.Controller.selectorLabels" . | nindent 20 }}
      {{- end }}
      containers:
      - name: {{ .Values.controller.name | trunc 63 | trimSuffix "-" }}
        image: {{ include "enipam.Controller.image" . | quote }}
        imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
        command:
        - {{ .Values.controller.binName }}
        args:
        - daemon
        - --config-path=/tmp/config-map/conf.yml
        {{- with .Values.controller.extraArgs }}
        {{- toYaml . | trim | nindent 8 }}
        {{- end }}
        ports:
        {{- if .Values.controller.prometheus.enabled }}
        - name: metrics
          containerPort: {{ .Values.controller.prometheus.port }}
          protocol: TCP
        {{- end }}
        - name: http
          containerPort: {{ .Values.controller.httpPort }}
          protocol: TCP
        - name: webhook
          containerPort: {{ .Values.controller.webhookPort }}
          protocol: TCP
        {{- with .Values.controller.resources }}
        resources:
        {{- toYaml . | trim | nindent 10 }}
        {{- end }}
        lifecycle:
          preStop:
            exec:
              command:
                - {{ .Values.controller.binName }}
                - shutdown
        env:
        - name: ENI_LOG_LEVEL
          value: {{ .Values.controller.debug.logLevel | quote }}
        - name: ENI_ENABLED_METRIC
          value: {{ .Values.controller.prometheus.enabled | quote }}
        - name: ENI_ENABLED_DEBUG_METRIC
          value: {{ .Values.controller.prometheus.enabledDebugMetric | quote }}
        - name: ENI_METRIC_HTTP_PORT
          value: {{ .Values.controller.prometheus.port | quote }}
        - name: ENI_GOPS_LISTEN_PORT
          value: {{ .Values.controller.debug.gopsPort | quote }}
        - name: ENI_TYPE
          value: {{ .Values.controller.infraType | quote }}
        - name: ENI_INFRA_TIMEOUT
          value: {{ .Values.controller.infraTimeout | quote }}
        - name: ENI_INFRAMUTEX
          value: {{ .Values.controller.infraMutex | quote }}
        - name: ENI_OPENSTACK_AUTH_URL
          value: {{ .Values.openstack.authUrl | quote }}
        - name: ENI_OPENSTACK_APPLICATION_CREDENTIAL_ID
          value: {{ .Values.openstack.applicationCredentialId | quote }}
        - name: ENI_OPENSTACK_APPLICATION_CREDENTIAL_SECRET
          value: {{ .Values.openstack.applicationCredentialSecret | quote }}
        - name: ENI_OPENSTACK_DEFAULT_SUBNAT_ID
          value: {{ .Values.openstack.defaultSubnatId | quote }}
        - name: ENI_OPENSTACK_DEFAULT_PROJECT_ID
          value: {{ .Values.openstack.defaultSubnatProjectId | quote }}
        - name: ENI_OPENSTACK_DEFAULT_REGION
          value: {{ .Values.openstack.authUrl | quote }}
        - name: ENI_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ENI_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- with .Values.controller.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.controller.securityContext }}
        securityContext:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
        - name: config-path
          mountPath: /tmp/config-map
          readOnly: true
      volumes:
      # To read the configuration from the config map
      - name: config-path
        configMap:
          name: {{ .Values.global.configName }}